<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <PropertyGroup>
    <ParallelCompilation>true</ParallelCompilation>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Utils.fs" />
    <Compile Include="QuerySpec.fs" />
    <Compile Include="CommandSpec.fs" />
    <Compile Include="HookSpec.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" Version="10.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\App.fsproj" />
  </ItemGroup>
</Project>
